steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/microservicios-476920/image-registry/products_ms",
        "-f",
        "dockerfile.prod",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/microservicios-476920/image-registry/products_ms",
      ]
options:
  logging: CLOUD_LOGGING_ONLY